### ISSUE TITLE
Cannot construct optional<T&> a different but compatible type of optional<U&>

### ISSUE THREAD

**Issue by tghosgor** [boostorg/optional#24]
Because it tries to access private ptr_ member of optional<U&> template from optional<T&> constructor.

**Comment by akrzemi1** [comment]
Thank you for the submission. If you can turn the commit into a pull request, I will be able to merge it.

**Comment by akrzemi1** [comment]
Oh, you did submit a pull request. Sorry. Already merged. Thanks!

**Comment by tghosgor** [comment]
Thank you for this useful library.
