### ISSUE TITLE
Forwarding ref. and variadic make_optional overloads missing

### ISSUE THREAD

**Issue by daniel-j-h** [boostorg/optional#30]
The stdlib provides forwarding ref. overloads and variadic template overloads for `make_optional`:
http://en.cppreference.com/w/cpp/utility/optional/make_optional

The same is missing from `boost::optional` at least from what I can tell (correct me if I'm wrong).

All I could find [here](https://github.com/boostorg/optional/blob/cb7641dc34bc61cefa44e9bccfebe02889148528/include/boost/optional/optional.hpp#L1279-L1293) are these two overloads:

```c++
optional<T> make_optional ( T const& v )
optional<T> make_optional ( bool cond, T const& v )
```

Which is sub-optimal since now users expecting a move will end up doing a copy instead:

```c++
boost::make_optional(std::move(bigObject)); // oops, calls T const& overload making a copy
```

cc @K-Ballo

**Comment by akrzemi1** [comment]
Indeed. The rvalue overloads are missing.
