### ISSUE TITLE
`boost::none` gets a separate instance in each translation unit

### ISSUE THREAD

**Issue by akrzemi1** [boostorg/optional#33]

**Comment by akrzemi1** [comment]
Provide a (still header-only) implementation that only renders a single instance of `boost::none`, e.g. using an enum.

**Comment by Lastique** [comment]
As commented in https://github.com/boostorg/core/issues/63#issuecomment-537450203, unscoped enums can implicitly convert to `int`, which can cause trouble with function overloads.

You may want to consider marking `none` with `inline` on C++17 compilers.
