### ISSUE TITLE
MSVC-12 fails to generate defaulted functions

### ISSUE THREAD

**Issue by Lastique** [boostorg/optional#38]
The issue appeared in Boost.Log tests. Apparently, MSVC-12 cannot generate defaulted move constructor and assignment operator:

```
D:\teeks99-09\run\boost_root\boost/optional/optional.hpp(968) : error C2610: 'boost::optional<T>::optional(boost::optional<T> &&)' : is not a special member function which can be defaulted
        D:\teeks99-09\run\boost_root\boost/optional/optional.hpp(1353) : see reference to class template instantiation 'boost::optional<T>' being compiled
D:\teeks99-09\run\boost_root\boost/optional/optional.hpp(1045) : error C2610: 'boost::optional<T> &boost::optional<T>::operator =(boost::optional<T> &&)' : is not a special member function which can be defaulted
```

This results in build failures.

**Comment by Lastique** [comment]
@jzmaddock As possible solution, we could define `BOOST_NO_CXX11_DEFAULTED_FUNCTIONS` for MSVC-12 in Boost.Config.

**Comment by pdimov** [comment]
Or add `BOOST_NO_CXX11_DEFAULTED_MOVE_FUNCTIONS`.

**Comment by Lastique** [comment]
@pdimov I'd rather not diversify `BOOST_NO_CXX11_DEFAULTED_FUNCTIONS` for compiler-specific bugs. This bug appears to be fairly specific, I'm not aware of other compilers with the same problem.

**Comment by pdimov** [comment]
It depends on the order in which support for defaulted functions and support for compiler-generated move is added to the compiler. It could be that msvc is the only one.

**Comment by pdimov** [comment]
According to https://gcc.gnu.org/projects/cxx-status.html, defaulted functions were added in 4.4, compiler-generated move in 4.6. Not very relevant nowadays, perhaps.

**Comment by akrzemi1** [comment]
I have submitted a patch to Boost.Config: https://github.com/boostorg/config/pull/205.

**Comment by Lastique** [comment]
Boost.Config PR has been merged, this is probably fixed.
