### ISSUE TITLE
regression: value-initialization of reference type

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/optional#43]
Travis is giving me this error:
https://travis-ci.org/vinniefalco/beast/jobs/297076642#L1379

The variable in question:
https://github.com/boostorg/beast/blob/e89814ff4ab871acc3c8387c9a0c4f0409b330c5/test/beast/core/buffered_read_stream.cpp#L59

**Comment by akrzemi1** [comment]
I reverted my changes from last weekend (with specializing optional for trivially copyable types). I expect your problems to go away.

**Comment by vinniefalco** [comment]
Sorry about that. I know you tried very hard to make it work. After 1.66.0 we will have more time to study it and see if we can bring back the optimization without the compile errors.

**Comment by akrzemi1** [comment]
That's precisely my plan. :)
