### ISSUE TITLE
Uninitialized scalar field (UNINIT_CTOR) in tc_optional_base

### ISSUE THREAD

**Issue by jeking3** [boostorg/optional#48]
This showed up on a Coverity Scan run in Boost.DateTime:

```
boost/optional/detail/optional_trivially_copyable_base.hpp: 

 protected:
 15    typedef T &       reference_type ;
 16    typedef T const&  reference_const_type ;
 17#ifndef  BOOST_OPTIONAL_DETAIL_NO_RVALUE_REFERENCES
 18    typedef T &&  rval_reference_type ;
 19    typedef T &&  reference_type_of_temporary_wrapper ;
 20#endif
 21    typedef T *         pointer_type ;
 22    typedef T const*    pointer_const_type ;
 23    typedef T const&    argument_type ;
 24
 25    tc_optional_base()
 26      :
   	
CID 202344 (#1-3 of 3): Uninitialized scalar field (UNINIT_CTOR)
2. uninit_member: Non-static class member m_storage is not initialized in this constructor nor in any functions that it calls.
 27      m_initialized(false) {}
 28
 29    tc_optional_base ( none_t )
 30      :
 31      m_initialized(false) {}
 32
 33    tc_optional_base ( argument_type val )
```

Coverity Scan issue id: 

https://scan4.coverity.com/reports.htm#v17121/p13946/fileInstanceId=35326295&defectInstanceId=6591221&mergedDefectId=202344

**Comment by akrzemi1** [comment]
This is on purpose. And I think it is ok to have uninitialized member provided that you do not read its value and  the only thing you do subsequently is to assign a different value to it.

**Comment by jeking3** [comment]
I will resolve this as intentional for performance.  Thanks!

**Comment by mglisse** [comment]
> And I think it is ok to have uninitialized member provided that you do not read its value and the only thing you do subsequently is to assign a different value to it.

Note that the uninitialized value can be read (copied) by a copy/move of the optional. But this base class is selected only for scalar types, and I expect this condition was chosen precisely so it would be safe to copy an uninitialized value (?). And copying is the only use that is made of the uninitialized value (and of its copies), so your argument should still hold.

**Comment by akrzemi1** [comment]
Technically, memcpy-ing an uninitialized scalar is UB.
