### ISSUE TITLE
Fix used of 0 as nullptr to avoid this warning -Wzero-as-null-pointer-constant

### ISSUE THREAD

**Issue by viboes** [boostorg/optional#49]
Hi, 
I'm compiling with -Werror,-Wzero-as-null-pointer-constant in clang-5.0.0 and getting

```
/Users/viboes/github/modular-boost3/boost/optional/detail/optional_reference_spec.hpp:139:172: error: zero as null pointer constant [-Werror,-Wzero-as-null-pointer-constant]
      optional(U& rhs, BOOST_DEDUCED_TYPENAME boost::enable_if_c<detail::is_same_decayed<T, U>::value && !detail::is_const_integral_bad_for_conversion<U>::value>::type* = 0) BOOST_NOEXCEPT
                                                                                                                                                                           ^
                                                                                                                                                                           nullptr

```
Please, could you fix it.
Vicente

**Comment by viboes** [comment]
Hrr, I forgot that Boost.Optional should work for C++03, so using `nullptr` there will not help.

Wondering if we need a BOOST_NULLPTR or a BOOST_NULLPTR_0 that solves the issue conditionally.

What do you think of something more elaborated as https://wandbox.org/permlink/auOe0MGi0cGLHla9 ? Do you see some liabilities other than the expressed via conditional compilation?

**Comment by akrzemi1** [comment]
I'll fix that. It is only used with `enable_if`s, so I can just change the pointers to type `bool`.

**Comment by viboes** [comment]
Yes, this is a better solution.

**Comment by akrzemi1** [comment]
The warnings should be gone now in branch `develop`

**Comment by viboes** [comment]
Thanks.

Please, close it as soon as it is merged to master.

**Comment by akrzemi1** [comment]
Merged.
