### ISSUE TITLE
Define std::hash<boost::optional<T>> for compat with std::optional

### ISSUE THREAD

**Issue by alexweej** [boostorg/optional#55]
[Edit] - title was updated, see comment 2 below:

Currently `boost::optional<T>` are not hashable, but `std::optional<T>` are.

`boost::variant<Ts...>` on the other hand *is* hashable. It seems fair that `boost::optional<T>` should have a `hash_value` ADL method.

Impl is fairly trivial, but it needs to be defined inside the boost namespace obviously so better to do it in Boost than in user code.

https://github.com/gcc-mirror/gcc/blob/edf8a7348075ec571536f44f9ae8c18bc1e02fed/libstdc%2B%2B-v3/include/std/optional#L1533

**Comment by alex-weej** [comment]
OK it seems I'm a bit confused here. Seems that both `boost::optional<T>` and `boost::variant<Ts...>` work well inside `boost::unordered_set<T>`. But neither work inside an `std::unordered_set<T>`. Is there anything that can be done in Boost to make them work out of the box with the **`std`** hashing protocol?

**Comment by akrzemi1** [comment]
Sure. We can specialize `std::hash`, as was done in this implementation of optional: https://github.com/akrzemi1/Optional/blob/f6249e7fdcb80131c390a083f1621d96023e72e9/optional.hpp#L1038

I have this recorded as a work item. But the deadline for features in 1.68 is now ended, so it will make it to 1.89, I think. In the meantime, you can specialize `std::hash` for `boost::optional` as in the enclosed link.

**Comment by alex-weej** [comment]
@akrzemi1 I assume you meant 1.69! :) Would you also agree this is reasonable for boost::variant, too then? I can file an issue there too but would be hoping for your support.

Thanks

**Comment by akrzemi1** [comment]
Yes, such addition makes sense for `boost::variant` as well.

**Comment by alex-weej** [comment]
Thanks @akrzemi1, much appreciate your work here. If there's anything I can do to help let me know.

**Comment by KermMartian** [comment]
Am I correct in thinking that `std::hash<boost::optional<T>>` is still pending?

**Comment by akrzemi1** [comment]
Unfortunately, you are. Sorry for the delay. I'll try to fix it over the weekend.

**Comment by akrzemi1** [comment]
This has now been implemented in branch develop. I would appreciate any feedback, if you can test it there.

**Comment by akrzemi1** [comment]
And now it is in master, heading for 1.80.
