### ISSUE TITLE
`reset()` marked as deprecated

### ISSUE THREAD

**Issue by Kojoley** [boostorg/optional#61]
It should be a mistake that `rest()` of `boost::optional` is marked as deprecated because `std::optional` has `reset()` [\[optional.mod\]](http://eel.is/c++draft/optional.mod).

The story behind this finding
---
I am working on adding `std::optional` support for Spirit and it requires rewriting of optional handling. Currently it resets optional with `boost::none` and I wanted to generalize this (as I do not see a reason why it should handle boost and std optional differently) because I cannot reset `std::optional` with `boost::none_t`. The `reset()` method serves perfectly for this purpose, but the problem is that for some reason `boost::optional` has `reset()` marked as deprecated.

**Comment by Kojoley** [comment]
> It needs unit-testing

https://github.com/boostorg/optional/blob/106f9aee5e574a092a06ae0cb3446b587c2eabb8/test/optional_test.cpp#L148-L160

https://github.com/boostorg/optional/blob/106f9aee5e574a092a06ae0cb3446b587c2eabb8/test/optional_test.cpp#L674-L699

> marking as `noexcept`

https://github.com/boostorg/optional/blob/106f9aee5e574a092a06ae0cb3446b587c2eabb8/include/boost/optional/optional.hpp#L383

https://github.com/boostorg/optional/blob/106f9aee5e574a092a06ae0cb3446b587c2eabb8/include/boost/optional/detail/optional_trivially_copyable_base.hpp#L132

https://github.com/boostorg/optional/blob/106f9aee5e574a092a06ae0cb3446b587c2eabb8/include/boost/optional/detail/old_optional_implementation.hpp#L337

https://github.com/boostorg/optional/blob/106f9aee5e574a092a06ae0cb3446b587c2eabb8/include/boost/optional/detail/optional_reference_spec.hpp#L159

> support in `optional<T&>`

https://github.com/boostorg/optional/blob/106f9aee5e574a092a06ae0cb3446b587c2eabb8/include/boost/optional/detail/optional_reference_spec.hpp#L159

**Comment by akrzemi1** [comment]
Right. Sorry for too shallow an investigation on my side. I merged the PR with some minor modifications in the documentation.

**Comment by Kojoley** [comment]
Thanks!
