### ISSUE TITLE
Please merge the 'develop' branch change into 'master' for the Boost 1.75 release

### ISSUE THREAD

**Issue by eldiener** [boostorg/optional#86]
A fix in the 'develop' branch is for the Embarcadero C++ clang-based compilers.

**Comment by akrzemi1** [comment]
I have just merged branch develop to master with https://github.com/boostorg/optional/commit/18222c83945f31dba749e232f27dba15bfe5e6d8.
Does that address your request?

**Comment by eldiener** [comment]
Yes, it does. Thank you !
