### ISSUE TITLE
Respect BOOST_NO_IOSTREAM

### ISSUE THREAD

**Issue by lebdron** [boostorg/optional#92]
It would be great to respect BOOST_NO_IOSTREAM by not defining `operator<<` in `optional.hpp` to avoid compilation issues with Google Test, similar to how it is done in Boost::Variant
https://github.com/boostorg/variant/blob/d80cb48f0294310ccba477923eedff93f9d73aa4/include/boost/variant/variant.hpp#L2452

**Comment by akrzemi1** [comment]
Thanks for reporting this. I have just pushed a commit to develop. Does this address your problem?

**Comment by lebdron** [comment]
Yes, looks perfect, thank you for the quick response!
